---
title: "Phenotype Analysis of Gardnerella spp."
author: "Spencer Toth"
date: "`r Sys.Date()`"
output: html_document
---
---
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(phylosignal)
library(broom)
library(rstatix)
library(adephylo)
library(ape)
library(phylobase)
library(formattable)
library(corrplot)
library(ggbeeswarm)
library(cowplot)
library(ggpubr)
library(grid)
library(gridGraphics)
library(ggplot2)
library(readr) 
library(dplyr)
library(tidyr)
library(patchwork)
`%!in%` <- negate(`%in%`)
```

## Prepare data for analysis 
Import phenotype data
```{r, message=FALSE, warning=FALSE, echo=TRUE}

# Import phenotypic data
carrying_capacity_data_file <- read_csv("/Users/spencertoth/Desktop/research_ongoing/gardnerella_phylogenetic_signal/gardnerella_pathogenic_phenotypes_1_24_2026/formatted_phenotype_data/carrying_capacity.csv")
growth_rate_data_file <- read_csv("/Users/spencertoth/Desktop/research_ongoing/gardnerella_phylogenetic_signal/gardnerella_pathogenic_phenotypes_1_24_2026/formatted_phenotype_data/growth_rate.csv") 
percent_biofilm_od_data_file <- read_csv("/Users/spencertoth/Desktop/research_ongoing/gardnerella_phylogenetic_signal/gardnerella_pathogenic_phenotypes_1_24_2026/formatted_phenotype_data/percent_biofilm_od.csv")  
pH_growth_data_file <- read_csv("/Users/spencertoth/Desktop/research_ongoing/gardnerella_phylogenetic_signal/gardnerella_pathogenic_phenotypes_1_24_2026/formatted_phenotype_data/pH_growth.csv")  
safranin_od_data_file <- read_csv("/Users/spencertoth/Desktop/research_ongoing/gardnerella_phylogenetic_signal/gardnerella_pathogenic_phenotypes_1_24_2026/formatted_phenotype_data/safranin_od.csv") 
```

Average the phenotype values across technical replicates per strain  
```{r, message=FALSE, warning=FALSE, echo=TRUE}
carrying_capacity_data <- carrying_capacity_data_file %>%
  mutate(Strain = as.character(Strain)) %>%
  group_by(Strain) %>% summarise(mean_maxOD = mean(maxOD, na.rm = TRUE))
cc_vector <- setNames(carrying_capacity_data$mean_maxOD, carrying_capacity_data$Strain)
cc_range <- range(cc_vector, na.rm = TRUE)
# Carrying Capacity: CV amongst strains 
cc_cv_between <- (sd(cc_vector) / mean(cc_vector)) 
cat(cc_cv_between)


growth_rate_data <- growth_rate_data_file %>%
  mutate(Strain = as.character(Strain)) %>%
  group_by(Strain) %>% summarise(mean_mSlope = mean(mSlope, na.rm = TRUE))
gr_vector <- setNames(growth_rate_data$mean_mSlope, growth_rate_data$Strain)
gr_range <- range(gr_vector, na.rm = TRUE)
# Growth rate: CV amongst strains 
gr_cv_between <- (sd(gr_vector) / mean(gr_vector)) 
cat(gr_cv_between)

# Transform percent_biofilm by applying asin(sqrt(x))
percent_biofilm_od_data <- percent_biofilm_od_data_file %>%
  mutate(Strain = as.character(Strain),
         arcsq_mPercentOD = asin(sqrt(mPercentOD/100))) %>%
  group_by(Strain) %>% 
  summarise(mean_arcsq_mPercentOD = mean(arcsq_mPercentOD, na.rm = TRUE))   
pb_vector <- setNames(percent_biofilm_od_data$mean_arcsq_mPercentOD, percent_biofilm_od_data$Strain)
pb_range <- range(pb_vector, na.rm = TRUE)
# Percent Biofilm: CV amongst strains 
pb_cv_between <- (sd(pb_vector) / mean(pb_vector)) 
cat(pb_cv_between) 


safranin_od_data <- safranin_od_data_file %>%
  mutate(Strain = as.character(Strain)) %>%
  group_by(Strain) %>% summarise(mean_mSafOD = mean(mSafOD, na.rm = TRUE))
sf_vector <- setNames(safranin_od_data$mean_mSafOD, safranin_od_data$Strain)
sf_range <- range(sf_vector, na.rm = TRUE)
# Safranin: CV amongst strains 
sf_cv_between <- (sd(sf_vector) / mean(sf_vector)) 
cat(sf_cv_between) 
```

Using t-test to identify the minimum pH value where non-zero growth (>0.01) occurred for each strain
```{r, message=FALSE, warning=FALSE, echo=TRUE}
pH_growth_data <- pH_growth_data_file %>%
  group_by(Strain, pH) %>%
  t_test(mOD ~ 1, mu = 0.01, alternative = "greater") %>%
  add_significance("p") %>%
  filter(p.signif != "ns") %>%
  group_by(Strain) %>%
  filter(pH == min(pH)) %>%
  mutate(pH = as.numeric(pH))
ph_vector <- setNames(pH_growth_data$pH, pH_growth_data$Strain)
ph_range <- range(ph_vector, na.rm = TRUE)
# Min pH: CV amongst strains 
ph_cv <- (sd(ph_vector) / mean(ph_vector)) * 100
cat(ph_cv)  # CV across strains (%)
```

Rename complete-numeric strains  
```{r, message=FALSE, warning=FALSE, echo=TRUE}
# Strain 14018 not present in: pb_vector, sf_vector (did not pass QC for these experiments)
vecs <- list(ph=ph_vector, cc=cc_vector, gr=gr_vector)
vecs[] <- lapply(vecs, function(v) {
  idx <- names(v) == "14018"   
  if(any(idx)) names(v)[idx] <- "S14018"   
  v
})

({cc_vector<<-vecs$cc; gr_vector<<-vecs$gr; ph_vector<<-vecs$ph})
names(ph_vector)
```

## Phenotype Distribution Visualizations
Plot distribution of values for each phenotype on histogram
```{r, message=FALSE, warning=FALSE}
# Compute ranges for each dataset
p1 <- ggplot(carrying_capacity_data, aes(x = mean_maxOD)) +
  geom_histogram(binwidth = 0.05, color = "black", fill = "#0072B2") +
  geom_text(stat = "bin", binwidth = 0.05, 
            aes(label = ifelse(after_stat(count) == 0, "", after_stat(count))), 
            position = position_stack(vjust = 0.8), 
            color = "black", size = 5) +
  coord_cartesian(xlim = c(cc_range[1] - 0.05, cc_range[2] + 0.05)) +
  scale_x_continuous(breaks = pretty(cc_range, n = 10)) +
  labs(title = "Carrying Capacities", 
      subtitle = "Measured as max OD600 over incubation period; n = 22",
       x = "Average max OD600", y = "Number of Strains") +
  theme(axis.text.x = element_text(size = 12, colour = "black"),
        plot.title = element_text(hjust = 0.5))   

p2 <- ggplot(growth_rate_data, aes(x = mean_mSlope)) +
  geom_histogram(binwidth = 0.05, color = "black", fill = "#E69F00") +
  geom_text(stat = "bin", binwidth = 0.05, 
            aes(label = ifelse(after_stat(count) == 0, "", after_stat(count))), 
            position = position_stack(vjust = 0.8), 
            color = "black", size = 5) +
  coord_cartesian(xlim = c(gr_range[1] - 0.05, gr_range[2] + 0.05)) +
  scale_x_continuous(breaks = pretty(gr_range, n = 10)) +
  labs(title = "Exponential Growth Rate",
       subtitle = "n = 22",
       x = "Average growth rates", y = "Number of Strains") +
  theme(axis.text.x = element_text(size = 12, colour = "black"),
        plot.title = element_text(hjust = 0.5))   
 
p3 <- ggplot(pH_growth_data, aes(x = pH)) +
  geom_histogram(binwidth = 0.25, color = "black", fill = "#009E73") +
  geom_text(stat = "bin", binwidth = 0.05, 
            aes(label = ifelse(after_stat(count) == 0, "", after_stat(count))), 
            position = position_stack(vjust = 0.8), 
            color = "black", size = 5) +
  coord_cartesian(xlim = c(ph_range[1] - 0.1, ph_range[2] + 0.1)) +
   scale_x_continuous(breaks = pretty(ph_range, n = 5)) +
  labs(title = "Minimum pH with Growth",
      subtitle = "Lowest pH (3.5 - 6) with OD600 >= 0.01; n = 22",
       x = "Average minimum pH", y = "Number of Strains") +
  theme(axis.text.x = element_text(size = 12, colour = "black"),
        plot.title = element_text(hjust = 0.5))  
       
p4 <- ggplot(percent_biofilm_od_data, aes(x = mean_arcsq_mPercentOD)) +
  geom_histogram(binwidth = 0.04, color = "black", fill = "#D55E00") +  
  geom_text(stat = "bin", binwidth = 0.04, 
            aes(label = ifelse(after_stat(count) > 0, after_stat(count), "")), 
            position = position_stack(vjust = 0.8), 
            color = "black", size = 4) +  
  coord_cartesian(xlim = c(pb_range[1] - 0.1, pb_range[2] + 0.1)) +  
  scale_x_continuous(breaks = pretty(pb_range, n = 10)) +   
  labs(title = "Biofilm Formation: Percent Growth as Biofilm",
       subtitle = paste("n =", nrow(percent_biofilm_od_data)),
       x = "Mean Arcsine-Sqrt(Percent Biofilm)", 
       y = "Number of Strains") +
  theme(axis.text.x = element_text(size = 12, colour = "black"),
        plot.title = element_text(hjust = 0.5))  


p5 <- ggplot(safranin_od_data, aes(x = mean_mSafOD)) +
  geom_histogram(binwidth = 0.05, color = "black", fill = "#CC79A7") +
  geom_text(stat = "bin", binwidth = 0.05, 
            aes(label = ifelse(after_stat(count) == 0, "", after_stat(count))), 
            position = position_stack(vjust = 0.8), 
            color = "black", size = 5) +
  coord_cartesian(xlim = c(sf_range[1] - 0.1, sf_range[2] + 0.1))  +
  scale_x_continuous(breaks = pretty(sf_range, n = 10)) +
  labs(title = "Biofilm Formation: OD450 of Safranin Stain", 
       subtitle = "n = 21",
       x = "Average OD450", y = "Number of Strains") +
  theme(axis.text.x = element_text(size = 12, colour = "black"),
        plot.title = element_text(hjust = 0.5))  


print(p1); print(p2); print(p3); print(p4); print(p5)
```
